### ISSUE TITLE
Run training across multiple GPUs and multiple nodes on Baskerville

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/aurora-hpc#16]
Run training in two scenarios on Baskerville:
1. Across four GPUs on a single node.
2. Across eight GPUs on two nodes.

Compare the timing and GPU usage results to check things are working as expected.

Compare the results with those from #17 on DAWN to see whether there are any obvious differences.

**Comment by llewelld** [comment]
Results for 4 nodes $\times$ 1 GPUs $\times$ 80 GiB/GPU (4 $\times$ GPUs total). This is again to try to understand if the GPU split across nodes makes a difference. I've added the results to the table above.

```yaml
Gathered times: [51.436474, 5.3352427, 6.7257185, 6.824637, 6.931211, 6.381731, 6.2135444, 6.2986994, 51.527027, 5.391185, 6.6904163, 6.7890406, 7.0007687, 6.267307, 6.3372684, 6.261259, 51.415836, 6.0909452, 6.839595, 6.9837847, 6.3665905, 6.240034, 6.2680664, 6.3433604, 51.526344, 5.525399, 6.625211, 6.907911, 6.76586, 6.383403, 6.240851, 6.3073187]
Gathered times: [51.436474, 5.3352427, 6.7257185, 6.824637, 6.931211, 6.381731, 6.2135444, 6.2986994, 51.527027, 5.391185, 6.6904163, 6.7890406, 7.0007687, 6.267307, 6.3372684, 6.261259, 51.415836, 6.0909452, 6.839595, 6.9837847, 6.3665905, 6.240034, 6.2680664, 6.3433604, 51.526344, 5.525399, 6.625211, 6.907911, 6.76586, 6.383403, 6.240851, 6.3073187]
done
Gathered times: [51.436474, 5.3352427, 6.7257185, 6.824637, 6.931211, 6.381731, 6.2135444, 6.2986994, 51.527027, 5.391185, 6.6904163, 6.7890406, 7.0007687, 6.267307, 6.3372684, 6.261259, 51.415836, 6.0909452, 6.839595, 6.9837847, 6.3665905, 6.240034, 6.2680664, 6.3433604, 51.526344, 5.525399, 6.625211, 6.907911, 6.76586, 6.383403, 6.240851, 6.3073187]
done
Gathered times: [51.436474, 5.3352427, 6.7257185, 6.824637, 6.931211, 6.381731, 6.2135444, 6.2986994, 51.527027, 5.391185, 6.6904163, 6.7890406, 7.0007687, 6.267307, 6.3372684, 6.261259, 51.415836, 6.0909452, 6.839595, 6.9837847, 6.3665905, 6.240034, 6.2680664, 6.3433604, 51.526344, 5.525399, 6.625211, 6.907911, 6.76586, 6.383403, 6.240851, 6.3073187]
done
Average time per epoch (ignoring first): 6.404870510101318
Total time for 32 epochs: 385.2420349121094
Total time: 118.9853572845459
done
```
A sample of the GPU utilisation:

```tsv
#Date        Time         gpu    pwr  gtemp  mtemp     sm    mem    enc    dec    jpg    ofa   mclk   pclk  rxpci  txpci
#YYYYMMDD    HH:MM:SS     Idx      W      C      C      %      %      %      %      %      %    MHz    MHz   MB/s   MB/s
 20250703    11:01:49       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:50       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:51       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:53       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:54       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:55       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:56       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:57       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:58       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:01:59       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:02:00       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:02:01       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:02:02       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:02:03       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:02:04       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
 20250703    11:02:05       0     77     31     48      0      0      0      0      0      0   1593   1275      0      0
```
